name:                toolset
version:             0.1.0.0
github:              "arademaker/toolset"
license:             BSD3
author:              "Alexandre Rademaker"
maintainer:          "arademaker@gmail.com"
copyright:           "2021 Alexandre Rademaker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arademaker/toolset#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  toolset-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toolset

tests:
  toolset-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toolset
